Messages when register
dyl10s/TimeTracker pull request #181
Opened 2021-04-12 22:43 UTC by adamchlebek

2021-04-13 17:58 UTC, dyl10s requested changes
I did not get any message when I registered, I also think there should be a specific message for when you try and join an archived project.

2021-04-15 14:29 UTC, jwaltt55 commented
We should probably have a message that indicates a user is already part of a project if they try to join one they've already joined, as of right now I just get a message saying that joining was successful.

2021-04-15 14:40 UTC, jwaltt55 commented
This is also kind of a nitpicky thing but I think it'd be more helpful to a user to have the error message for an invalid invite code to be something a little more specific. "Invite code hasn't been found" would probably seem kind of vague to just the average user I think.

2021-04-16 15:10 UTC, jwaltt55 commented
It looks like if you use the invite code with the login/register URLs while already logged in, you'll just get a "Invite code is invalid" message every time if you can't join the project, instead of the messages telling the user that they've already joined a project or that the project is archived. We probably want the error messages to be the same for both when the user has to login/register, and when they use the invite code while already logged in.

2021-04-16 15:31 UTC, dyl10s requested changes, later dismissed

2021-04-16 15:31 UTC, dyl10s commented on Frontend/src/app/views/auth/login/login.component.ts
> +                this.toastrService.danger("User is already assigned to this project", "Error");
I feel like this wording is a bit off, we are talking directly to the user this seems more of like a backend logging message.

2021-04-18 23:10 UTC, jwaltt55 commented
Just a couple small things:

There's a typo for when you first login with an invite code (should be "a part" not "apart").

Also just in general I think the messages for when you use the invite code with a login/register endpoint when you're already logged in and when you're not logged in/haven't made an account yet should be the same, it's good that they're more specific now for when you're already logged in but they're kinda inconsistent with the messages you get if you're not logged in yet.

I'm also still getting the "user was successfully added to a project" message instead of the "you're already a part of this project" message sometimes, usually when I create a project and the immediately try to join it with an invite code a second time.

2021-04-19 05:18 UTC, jwaltt55 approved these changes

2021-04-19 05:34 UTC, merged