Help buttons
dyl10s/TimeTracker pull request #189
Opened 2021-04-18 01:19 UTC by jwaltt55

2021-04-18 01:38 UTC, dyl10s requested changes
It looks a bit weird on mobile, maybe if it covered the whole page and had some margin it would be better?

![image](https://user-images.githubusercontent.com/12243691/115131291-f7849600-9fc4-11eb-9240-6eb6e2dac554.png)

Also instead of repeating this html and css on the different components that needed it what about breaking it into its own component so you can just write like

```
<help-icon>
    This is the help text here <br/>
    this would eliminate repeated code  
</help-icon>
```

2021-04-18 01:44 UTC, dyl10s commented on Frontend/src/app/views/dashboard/report-details/report-details.component.html
> +        Clicking on the date boxes will also let you change the date range by typing in a new date or using the calander menu.<br><br>
Typo `calander`

2021-04-18 01:44 UTC, dyl10s commented on Frontend/src/app/views/dashboard/report/report.component.html
> +            Clicking on the date boxes will also let you change the date range by typing in a new date or using the calander menu.<br><br>
typo `calander`

2021-04-19 00:52 UTC, dyl10s requested changes

2021-04-19 00:52 UTC, dyl10s commented on Frontend/src/app/views/dashboard/project-details/project-details.component.scss
> +}
Remove this change

2021-04-19 00:52 UTC, dyl10s commented on Frontend/src/app/views/dashboard/projects/projects.component.ts
> +import { NbPopoverDirective } from '@nebular/theme';
Do you still need this import?

2021-04-19 00:52 UTC, dyl10s commented on Frontend/src/app/views/dashboard/report-details/report-details.component.scss
> +}
Remove this change

2021-04-19 00:52 UTC, dyl10s commented on Frontend/src/app/views/dashboard/report/report.component.scss
> +}
Remove this change

2021-04-19 00:52 UTC, dyl10s commented on Frontend/src/app/views/dashboard/time/time.component.scss
> +}
Remove this change

2021-04-19 02:04 UTC, dyl10s approved these changes

2021-04-19 02:06 UTC, TonyCP approved these changes

2021-04-19 02:36 UTC, merged