Angular auth services
dyl10s/TimeTracker pull request #26
Opened 2021-02-11 00:01 UTC by adamchlebek

2021-02-11 00:08 UTC, dyl10s reviewed
Just wondering why interfaces here. Don't we then have to implement them? Maybe interfaces are different in typescript and I am just not understanding.

2021-02-11 00:12 UTC, dyl10s reviewed
Also, I am thinking we should expand the scope of these service stories. I originally thought this was going to be basically making the design happen / all the typescript logic coding behind the designs. If that's not the case here, we will need to create additional stories for that.

2021-02-11 00:42 UTC, adamchlebek commented
> Just wondering why interfaces here. Don't we then have to implement them? Maybe interfaces are different in typescript and I am just not understanding.

For interfaces in TypeScript, this is just used for structuring. Here is a good link that explains it:

[StackOverflow](https://stackoverflow.com/questions/51716808/when-use-a-interface-or-class-in-typescript)

2021-02-11 00:43 UTC, adamchlebek commented
> Also, I am thinking we should expand the scope of these service stories. I originally thought this was going to be basically making the designs functional aka all the typescript logic coding behind the designs. If that's not the case here, we will need to create additional stories for that.

I can keep this PR open and wait for the front end changes. I forgot about adding all the logic behind it. For now, we can keep this open and wait for design stuff to be finished.

2021-02-11 01:18 UTC, dyl10s commented
> > Just wondering why interfaces here. Don't we then have to implement them? Maybe interfaces are different in typescript and I am just not understanding.
> 
> For interfaces in TypeScript, this is just used for structuring. Here is a good link that explains it:
> 
> [StackOverflow](https://stackoverflow.com/questions/51716808/when-use-a-interface-or-class-in-typescript)

Interesting kinda the nature of js your basically implementing them when you pass them. Cool!

2021-02-17 01:18 UTC, dyl10s requested changes
In slow network conditions it can be a bit weird if there is no loading indicator, could you make the buttons turn into spinners while the API request is made? Or if you have another solution that's fine too. Just something to let the user know the page is loading.

2021-02-17 01:18 UTC, dyl10s commented on Frontend/src/app/auth/pages/register/register.component.ts
> +    });
Need some error message here if there is a failure to connect to the API

2021-02-17 01:18 UTC, dyl10s commented on Frontend/src/app/auth/pages/login/login.component.ts
> +    });
Need an error here if there is a failure to connect to the api

2021-02-17 03:40 UTC, dyl10s commented on Frontend/src/app/auth/pages/register/register.component.html
> +              nbSpinnerStatus="danger">
I feel like green would look better here than red, what do you think? Red is a scary color.

2021-02-17 03:40 UTC, dyl10s commented on Frontend/src/app/auth/pages/login/login.component.html
> +              nbSpinnerStatus="danger">
I feel like green would look better here than red, what do you think? Red is a scary color.

2021-02-17 03:47 UTC, dyl10s approved these changes

2021-02-17 03:50 UTC, merged