started work on bug fix
dyl10s/TimeTracker pull request #77
Opened 2021-03-03 17:41 UTC by jwaltt55

2021-03-03 23:56 UTC, dyl10s requested changes

2021-03-03 23:56 UTC, dyl10s commented on Frontend/src/app/views/auth/login/login.component.ts
> +            console.log(paramMap);
You can remove this

2021-03-03 23:56 UTC, dyl10s commented on Frontend/src/app/views/auth/login/login.component.ts
>          // TODO: Remove alert and route to dashboard
This is a really old comment. Might as well remove this too.

2021-03-04 15:19 UTC, dyl10s approved these changes
I am fine with this implementation, it makes sense to me to have it here. I'll approve this but just check with @adamchlebek before merging.

2021-03-05 17:31 UTC, adamchlebek approved these changes

2021-03-05 17:38 UTC, merged